server:
  port: 8082

spring:
  application:
    name: PatientIntakeService
  datasource:
    url: jdbc:postgresql://localhost:5432/clinic_management_patientintake_service
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


services:
  doctor-schedule:
    base-url: http://localhost:8081/api/v1/schedules

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html